DO $$ BEGIN CREATE TYPE listing_state AS ENUM ('active','filter_rejected','ai_rejected','manually_rejected','restored','archived'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE override_action AS ENUM ('restore','reject'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
-- Core tables match the application EF migration. CREATE IF NOT EXISTS only bootstraps isolated exporter tests;
-- production runs application migrations first.
CREATE TABLE IF NOT EXISTS listings (
    "Id" uuid PRIMARY KEY, "ExternalId" text NOT NULL, "Address" text NOT NULL,
    "City" text, "Price" numeric(14,2), "FamilyFitScore" double precision NOT NULL,
    "State" listing_state NOT NULL, "AiAssessed" boolean NOT NULL,
    "AiConfidence" double precision, "AiEvidence" text, "ModelVersion" text,
    "RuleVersion" text, "SourceUrl" text, "ImportedAt" timestamptz NOT NULL,
    "ArchivedAt" timestamptz, "PreviewImageUrl" text, "LivingArea" integer,
    "LotArea" integer, "Rooms" integer, "YearBuilt" integer, "Bathrooms" integer,
    "Bedrooms" integer, "Floors" integer, "EnergyLabel" text, "Quiet" boolean,
    "BuildableHeadroom" integer, "GroundFloorBedroom" boolean,
    "SeparateEntrance" boolean, "SecondKitchen" boolean, "PrivacyScore" integer,
    "FamilyPrivacyScore" double precision, "KidsSpaceScore" double precision,
    "GardenScore" double precision, "SharedLivingScore" double precision,
    "PracticalScore" double precision, "FamilyPrivacyWeight" double precision,
    "KidsSpaceWeight" double precision, "GardenWeight" double precision,
    "SharedLivingWeight" double precision, "PracticalWeight" double precision,
    "Latitude" double precision, "Longitude" double precision,
    "MonthlyExpense" integer, "DaysOnMarket" integer, "CommuteMinutes" integer,
    "BuildableStatus" text, "Condition" text, "GardenOrientation" text, "MultigenFit" text,
    "PostalCode" text, "Preferred" boolean, "IsNew" boolean, "FamilyUnits" text, "LearningRuleVersion" text
);
ALTER TABLE listings ADD COLUMN IF NOT EXISTS "PreviewImageUrl" text;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS "LivingArea" integer;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS "LotArea" integer;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS "Rooms" integer;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS "YearBuilt" integer;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS "Bathrooms" integer;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS "Bedrooms" integer;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS "Floors" integer;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS "EnergyLabel" text;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS "Quiet" boolean;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS "BuildableHeadroom" integer;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS "GroundFloorBedroom" boolean;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS "SeparateEntrance" boolean;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS "SecondKitchen" boolean;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS "PrivacyScore" integer;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS "FamilyPrivacyScore" double precision;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS "KidsSpaceScore" double precision;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS "GardenScore" double precision;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS "SharedLivingScore" double precision;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS "PracticalScore" double precision;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS "FamilyPrivacyWeight" double precision;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS "KidsSpaceWeight" double precision;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS "GardenWeight" double precision;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS "SharedLivingWeight" double precision;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS "PracticalWeight" double precision;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS "Latitude" double precision;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS "Longitude" double precision;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS "MonthlyExpense" integer;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS "DaysOnMarket" integer;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS "CommuteMinutes" integer;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS "BuildableStatus" text;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS "Condition" text;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS "GardenOrientation" text;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS "MultigenFit" text;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS "LearningRuleVersion" text;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS "PostalCode" text;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS "Preferred" boolean;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS "IsNew" boolean;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS "FamilyUnits" text;
CREATE UNIQUE INDEX IF NOT EXISTS "IX_listings_ExternalId" ON listings ("ExternalId");
CREATE TABLE IF NOT EXISTS listing_overrides (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ListingId" uuid NOT NULL REFERENCES listings("Id") ON DELETE RESTRICT,
    "OwnerId" uuid NOT NULL, "Action" override_action NOT NULL,
    "Reason" text, "CreatedAt" timestamptz NOT NULL
);
CREATE TABLE IF NOT EXISTS export_runs (
    run_id text PRIMARY KEY, source_scope text NOT NULL,
    fetched_at timestamptz NOT NULL, completed_at timestamptz
);
CREATE TABLE IF NOT EXISTS listing_export_state (
    listing_id uuid PRIMARY KEY REFERENCES listings("Id") ON DELETE RESTRICT,
    source_scope text NOT NULL, first_seen_at timestamptz NOT NULL,
    last_seen_at timestamptz NOT NULL, last_seen_run_id text NOT NULL,
    non_ai_passed boolean NOT NULL, pipeline_decision text NOT NULL,
    archive_reason text, raw_payload jsonb NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_listing_export_state_scope_run ON listing_export_state(source_scope,last_seen_run_id);
CREATE TABLE IF NOT EXISTS listing_imports (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    listing_id uuid NOT NULL REFERENCES listings("Id") ON DELETE RESTRICT,
    run_id text NOT NULL REFERENCES export_runs(run_id) ON DELETE RESTRICT,
    imported_at timestamptz NOT NULL, payload_sha256 text NOT NULL,
    raw_payload jsonb NOT NULL, non_ai_passed boolean NOT NULL,
    pipeline_decision text NOT NULL, UNIQUE (listing_id, run_id)
);
CREATE TABLE IF NOT EXISTS ai_evidence (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    listing_id uuid NOT NULL REFERENCES listings("Id") ON DELETE RESTRICT,
    run_id text NOT NULL REFERENCES export_runs(run_id) ON DELETE RESTRICT,
    decision text NOT NULL, confidence text, model_version text NOT NULL,
    rule_version text NOT NULL, evidence jsonb NOT NULL,
    evidence_sha256 text NOT NULL, created_at timestamptz NOT NULL,
    UNIQUE (listing_id, run_id)
);
CREATE TABLE IF NOT EXISTS listing_media (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    listing_id uuid NOT NULL REFERENCES listings("Id") ON DELETE RESTRICT,
    kind text NOT NULL CHECK (kind IN ('thumbnail','floorplan')),
    source_url text NOT NULL, local_path text NOT NULL, content_type text,
    content_sha256 text NOT NULL, byte_size bigint NOT NULL,
    cached_at timestamptz NOT NULL, UNIQUE (listing_id,kind,source_url)
);
