using HouseConsensus.Server.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable
namespace HouseConsensus.Server.Data.Migrations;

[DbContext(typeof(AppDbContext)), Migration("202607310002_AddManualListingsAndGuidedVoting")]
public sealed class AddManualListingsAndGuidedVoting : Migration
{
    protected override void Up(MigrationBuilder m) => m.Sql("""
DO $$ BEGIN CREATE TYPE vote_category AS ENUM ('layout','privacy','garden','condition','location','noise','price','multi_generation_fit','commute','buildability'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE category_rating AS ENUM ('dislike','neutral','like'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE listings ALTER COLUMN "FamilyFitScore" DROP NOT NULL;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS "CanonicalUrl" character varying(2048);
ALTER TABLE listings ADD COLUMN IF NOT EXISTS "NormalizedAddress" character varying(500);
ALTER TABLE listings ADD COLUMN IF NOT EXISTS "IsManuallyAdded" boolean NOT NULL DEFAULT false;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS "ManuallyAddedById" uuid;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS "ManuallyAddedAt" timestamp with time zone;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS "ManualLifecycleProtected" boolean NOT NULL DEFAULT false;
DO $$ BEGIN ALTER TABLE listings ADD CONSTRAINT "FK_listings_members_ManuallyAddedById" FOREIGN KEY ("ManuallyAddedById") REFERENCES members("Id") ON DELETE RESTRICT; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
WITH normalized AS (
  SELECT "Id", replace(lower(regexp_replace(btrim("Address"), '\s+', ' ', 'g')), ' ,', ',') AS value,
         row_number() OVER (PARTITION BY replace(lower(regexp_replace(btrim("Address"), '\s+', ' ', 'g')), ' ,', ',') ORDER BY "ImportedAt", "Id") AS rank
  FROM listings WHERE "NormalizedAddress" IS NULL
)
UPDATE listings l SET "NormalizedAddress"=n.value FROM normalized n
WHERE l."Id"=n."Id" AND n.rank=1 AND length(n.value) <= 500
  AND NOT EXISTS (SELECT 1 FROM listings occupied WHERE occupied."NormalizedAddress"=n.value);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_listings_CanonicalUrl" ON listings ("CanonicalUrl") WHERE "CanonicalUrl" IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS "IX_listings_NormalizedAddress" ON listings ("NormalizedAddress") WHERE "NormalizedAddress" IS NOT NULL;
CREATE INDEX IF NOT EXISTS "IX_listings_ManuallyAddedById" ON listings ("ManuallyAddedById");
CREATE TABLE IF NOT EXISTS vote_ratings (
  "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "VoteId" bigint NOT NULL REFERENCES votes("Id") ON DELETE RESTRICT,
  "Category" vote_category NOT NULL,
  "Rating" category_rating NOT NULL,
  CONSTRAINT "UX_vote_ratings_vote_category" UNIQUE ("VoteId", "Category")
);
INSERT INTO vote_ratings ("VoteId", "Category", "Rating")
SELECT v."Id", c.category,
 CASE WHEN
   (c.category = 'layout' AND 'layout'::reason_tag = ANY(v."Tags")) OR
   (c.category = 'privacy' AND ('privacy'::reason_tag = ANY(v."Tags") OR 'privacy_from_neighbors'::reason_tag = ANY(v."Tags"))) OR
   (c.category = 'garden' AND 'garden'::reason_tag = ANY(v."Tags")) OR
   (c.category = 'condition' AND 'condition'::reason_tag = ANY(v."Tags")) OR
   (c.category = 'location' AND 'location'::reason_tag = ANY(v."Tags")) OR
   (c.category = 'noise' AND 'noise'::reason_tag = ANY(v."Tags")) OR
   (c.category = 'price' AND 'price'::reason_tag = ANY(v."Tags"))
 THEN CASE WHEN v."Choice" = 'like'::vote_choice THEN 'like'::category_rating ELSE 'dislike'::category_rating END
 ELSE 'neutral'::category_rating END
FROM votes v CROSS JOIN unnest(enum_range(NULL::vote_category)) AS c(category)
ON CONFLICT ("VoteId", "Category") DO NOTHING;
""");

    protected override void Down(MigrationBuilder m) => throw new NotSupportedException("Manual provenance and immutable guided vote history cannot be safely removed.");
}
