using HouseConsensus.Server.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
namespace HouseConsensus.Server.Data.Migrations;

[DbContext(typeof(AppDbContext)), Migration("202607200001_InitialCreate")]
public sealed class InitialCreate : Migration
{
    protected override void Up(MigrationBuilder m) => m.Sql("""
CREATE TYPE member_role AS ENUM ('member','owner');
CREATE TYPE vote_choice AS ENUM ('like','dislike','not_voted');
CREATE TYPE listing_state AS ENUM ('active','filter_rejected','ai_rejected','manually_rejected','restored','archived');
CREATE TYPE reason_tag AS ENUM ('layout','privacy','garden','condition','location','noise','price','other');
CREATE TYPE override_action AS ENUM ('restore','reject');
CREATE TABLE members ("Id" uuid PRIMARY KEY,"Email" varchar(320) NOT NULL,"DisplayName" text NOT NULL,"Language" varchar(2) NOT NULL,"Role" member_role NOT NULL,"IsActive" boolean NOT NULL,"CreatedAt" timestamptz NOT NULL);
CREATE UNIQUE INDEX "IX_members_Email" ON members ("Email");
CREATE TABLE listings ("Id" uuid PRIMARY KEY,"ExternalId" text NOT NULL,"Address" text NOT NULL,"City" text NULL,"Price" numeric(14,2) NULL,"FamilyFitScore" double precision NOT NULL,"State" listing_state NOT NULL,"AiAssessed" boolean NOT NULL,"AiConfidence" double precision NULL,"AiEvidence" text NULL,"ModelVersion" text NULL,"RuleVersion" text NULL,"SourceUrl" text NULL,"ImportedAt" timestamptz NOT NULL,"ArchivedAt" timestamptz NULL);
CREATE UNIQUE INDEX "IX_listings_ExternalId" ON listings ("ExternalId"); CREATE INDEX "IX_listings_State_FamilyFitScore" ON listings ("State","FamilyFitScore");
CREATE TABLE listing_overrides ("Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"ListingId" uuid NOT NULL REFERENCES listings("Id") ON DELETE CASCADE,"OwnerId" uuid NOT NULL REFERENCES members("Id") ON DELETE RESTRICT,"Action" override_action NOT NULL,"Reason" text NULL,"CreatedAt" timestamptz NOT NULL); CREATE INDEX "IX_listing_overrides_ListingId_CreatedAt" ON listing_overrides("ListingId","CreatedAt");
CREATE TABLE votes ("Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"ListingId" uuid NOT NULL REFERENCES listings("Id") ON DELETE RESTRICT,"MemberId" uuid NOT NULL REFERENCES members("Id") ON DELETE RESTRICT,"Choice" vote_choice NOT NULL,"Tags" reason_tag[] NOT NULL,"CreatedAt" timestamptz NOT NULL); CREATE INDEX "IX_votes_ListingId_MemberId_CreatedAt" ON votes("ListingId","MemberId","CreatedAt");
CREATE TABLE comments ("Id" uuid PRIMARY KEY,"ListingId" uuid NOT NULL REFERENCES listings("Id") ON DELETE RESTRICT,"AuthorId" uuid NOT NULL REFERENCES members("Id") ON DELETE RESTRICT,"Body" varchar(4000) NOT NULL,"IsDeleted" boolean NOT NULL,"CreatedAt" timestamptz NOT NULL,"UpdatedAt" timestamptz NOT NULL); CREATE INDEX "IX_comments_ListingId_CreatedAt" ON comments("ListingId","CreatedAt");
CREATE TABLE comment_revisions ("Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"CommentId" uuid NOT NULL REFERENCES comments("Id") ON DELETE CASCADE,"PreviousBody" varchar(4000) NOT NULL,"ActorId" uuid NOT NULL REFERENCES members("Id") ON DELETE RESTRICT,"WasDeletion" boolean NOT NULL,"ChangedAt" timestamptz NOT NULL);
CREATE TABLE feedback ("Id" uuid PRIMARY KEY,"MemberId" uuid NOT NULL REFERENCES members("Id") ON DELETE RESTRICT,"ListingId" uuid NULL REFERENCES listings("Id") ON DELETE RESTRICT,"Body" varchar(4000) NOT NULL,"CreatedAt" timestamptz NOT NULL,"ReviewedAt" timestamptz NULL); CREATE INDEX "IX_feedback_CreatedAt" ON feedback("CreatedAt");
CREATE TABLE invites ("Id" uuid PRIMARY KEY,"Email" varchar(320) NOT NULL,"InvitedById" uuid NOT NULL REFERENCES members("Id") ON DELETE RESTRICT,"ExpiresAt" timestamptz NOT NULL,"AcceptedAt" timestamptz NULL); CREATE INDEX "IX_invites_Email" ON invites("Email");
CREATE TABLE magic_links ("Id" uuid PRIMARY KEY,"Email" varchar(320) NOT NULL,"TokenHash" varchar(64) NOT NULL,"ExpiresAt" timestamptz NOT NULL,"ConsumedAt" timestamptz NULL); CREATE UNIQUE INDEX "IX_magic_links_TokenHash" ON magic_links("TokenHash");
""");
    protected override void Down(MigrationBuilder m) => m.Sql("DROP TABLE IF EXISTS magic_links,invites,feedback,comment_revisions,comments,votes,listing_overrides,listings,members CASCADE; DROP TYPE IF EXISTS override_action,reason_tag,listing_state,vote_choice,member_role;");
}
