using HouseConsensus.Server.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable
namespace HouseConsensus.Server.Data.Migrations;
[DbContext(typeof(AppDbContext)), Migration("202607220003_AddVoteNotes")]
public sealed class AddVoteNotes : Migration
{
    protected override void Up(MigrationBuilder m) => m.Sql("""
ALTER TABLE votes ADD COLUMN "Note" varchar(2000) NULL;
CREATE TABLE vote_note_revisions (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "VoteId" bigint NOT NULL REFERENCES votes("Id") ON DELETE CASCADE,
    "PreviousNote" varchar(2000) NULL,
    "ActorId" uuid NOT NULL REFERENCES members("Id") ON DELETE RESTRICT,
    "ChangedAt" timestamptz NOT NULL
);
CREATE INDEX "IX_vote_note_revisions_VoteId" ON vote_note_revisions("VoteId");
""");
    protected override void Down(MigrationBuilder m) => m.Sql("""DROP TABLE vote_note_revisions; ALTER TABLE votes DROP COLUMN "Note";""");
}
