using HouseConsensus.Server.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable
namespace HouseConsensus.Server.Data.Migrations;
[DbContext(typeof(AppDbContext)), Migration("202607220007_HardenAiRuleAudit")]
public sealed class HardenAiRuleAudit : Migration
{
    protected override void Up(MigrationBuilder m) => m.Sql("""
ALTER TABLE ai_rule_proposals ADD COLUMN "PreviousProposalId" uuid NULL REFERENCES ai_rule_proposals("Id") ON DELETE RESTRICT;
CREATE UNIQUE INDEX "UX_ai_rule_proposals_one_active" ON ai_rule_proposals("IsActive") WHERE "IsActive";
CREATE TABLE ai_rule_proposal_actions (
    "Id" uuid PRIMARY KEY, "ProposalId" uuid NOT NULL REFERENCES ai_rule_proposals("Id") ON DELETE RESTRICT,
    "Action" varchar(40) NOT NULL, "ActorId" uuid NOT NULL REFERENCES members("Id") ON DELETE RESTRICT,
    "CreatedAt" timestamptz NOT NULL
);
CREATE INDEX "IX_ai_rule_proposal_actions_ProposalId_CreatedAt" ON ai_rule_proposal_actions("ProposalId", "CreatedAt");
CREATE TABLE ai_rule_applications (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ProposalId" uuid NOT NULL REFERENCES ai_rule_proposals("Id") ON DELETE RESTRICT,
    "ListingId" uuid NOT NULL REFERENCES listings("Id") ON DELETE RESTRICT,
    "PreviousState" listing_state NOT NULL, "PreviousLearningRuleVersion" text NULL,
    "AppliedState" listing_state NOT NULL, "AppliedAt" timestamptz NOT NULL,
    CONSTRAINT "UX_ai_rule_applications_ProposalId_ListingId" UNIQUE ("ProposalId", "ListingId")
);
""");
    protected override void Down(MigrationBuilder m) => m.Sql("""
DROP TABLE ai_rule_applications;
DROP TABLE ai_rule_proposal_actions;
DROP INDEX "UX_ai_rule_proposals_one_active";
ALTER TABLE ai_rule_proposals DROP COLUMN "PreviousProposalId";
""");
}
